//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.SRSolarIntensity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SolarIntensity")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRSolarIntensity.IServiceSolarIntensity")]
    public interface IServiceSolarIntensity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/GetData", ReplyAction="http://tempuri.org/IServiceSolarIntensity/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/GetData", ReplyAction="http://tempuri.org/IServiceSolarIntensity/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSolarIntensity/GetDataUsingDataContractResponse")]
        Assignment5.SRSolarIntensity.CompositeType GetDataUsingDataContract(Assignment5.SRSolarIntensity.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSolarIntensity/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Assignment5.SRSolarIntensity.CompositeType> GetDataUsingDataContractAsync(Assignment5.SRSolarIntensity.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/SolarIntensityService", ReplyAction="http://tempuri.org/IServiceSolarIntensity/SolarIntensityServiceResponse")]
        float SolarIntensityService(float latitude, float longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSolarIntensity/SolarIntensityService", ReplyAction="http://tempuri.org/IServiceSolarIntensity/SolarIntensityServiceResponse")]
        System.Threading.Tasks.Task<float> SolarIntensityServiceAsync(float latitude, float longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSolarIntensityChannel : Assignment5.SRSolarIntensity.IServiceSolarIntensity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSolarIntensityClient : System.ServiceModel.ClientBase<Assignment5.SRSolarIntensity.IServiceSolarIntensity>, Assignment5.SRSolarIntensity.IServiceSolarIntensity {
        
        public ServiceSolarIntensityClient() {
        }
        
        public ServiceSolarIntensityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSolarIntensityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSolarIntensityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSolarIntensityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Assignment5.SRSolarIntensity.CompositeType GetDataUsingDataContract(Assignment5.SRSolarIntensity.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Assignment5.SRSolarIntensity.CompositeType> GetDataUsingDataContractAsync(Assignment5.SRSolarIntensity.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public float SolarIntensityService(float latitude, float longitude) {
            return base.Channel.SolarIntensityService(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<float> SolarIntensityServiceAsync(float latitude, float longitude) {
            return base.Channel.SolarIntensityServiceAsync(latitude, longitude);
        }
    }
}
